import type { Faculty } from '../types.js'

export const REAL_FACULTY_ROSTER: Faculty[] = [
  { id: 'FAC-001', name: 'Dr.S.MALATHI', designation: 'Prof & Head', department: 'AI & DS', role: 'HOD', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-002', name: 'Dr.A.JOSHI', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-003', name: 'DR.T.KALAICHELVI', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-004', name: 'Dr.K.JAYASHREE', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-005', name: 'Dr.S.CHAKARAVARTHI', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-006', name: 'Dr.W.GRACY THERESA', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-007', name: 'Dr.N.SIVAKUMAR', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-008', name: 'Dr.T.VEERAMANI', designation: 'Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-009', name: 'Dr.C.GNANA PRAKASAM', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-010', name: 'Dr. C. BHARANI DHARAN', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-011', name: 'Dr.M.S MAHARAJAN', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-012', name: 'DR.E.BHUVANESWARI', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-013', name: 'Dr.LEELAVATHY', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-014', name: 'Mrs.S.VIMALA', designation: 'Assoc.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-015', name: 'Dr.C.VIVEK', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-016', name: 'DR. T. SELVA BANU PRIYA', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-017', name: 'Dr.M.VIDHYA SREE', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-018', name: 'Dr.V.MAHA VAISHNAVI', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-019', name: 'DR.D.S. SHAJI', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-020', name: 'MR. M. SADHASIVAM', designation: 'Asst.Prof G1', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-021', name: 'DR.V.RATHINAPRIYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-022', name: 'DR.S.SRINIDHI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-023', name: 'Mrs.R.PRIYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-024', name: 'MRS.BABISHA A', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-025', name: 'MRS.BALA ABIRAMI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-026', name: 'MRS.K.SARANYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-027', name: 'Mr.M.VETRISELVAN', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-028', name: 'Mrs.R.VIDHYA MUTHULAKSHMI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-029', name: 'MRS.V.REKHA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-030', name: 'MRS.S.SWATHI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-031', name: 'Mrs.J.ANITHA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-032', name: 'Mrs.GOMATHI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-033', name: 'Mrs.MEGALA . M', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-034', name: 'Ms.P.SHYAMALA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-035', name: 'MR.S.SURESH', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-036', name: 'MR.DEEPAK KUMAR', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-037', name: 'MRS.VASANTHI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-038', name: 'MR.R.SELVAM', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-039', name: 'MRS.GLORY SANGEETHA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-040', name: 'Mr.A.SANKARAN', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-041', name: 'MRS.S.PADMA PRIYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-042', name: 'Mrs.MAHALAKSHMI', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-043', name: 'MRS.SUGANYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-044', name: 'MS.S.SANDHIYA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-045', name: 'MS.SATHYABAMA', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-046', name: 'MRS.D.KALAIMANI', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-047', name: 'DR.N.R.RAM MOHAN', designation: 'Professor', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-048', name: 'MR.VIJAYAMAHENDRA VARMA', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-049', name: 'MS.J.SUGANYA DEVI', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-050', name: 'MRS.C.ANNAPOORANI', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-051', name: 'DR.S.RAVEENA', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-052', name: 'MS.R.VAISHNAVI', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-053', name: 'MRS.P.RANJIDHA', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-054', name: 'MR.P.KALIAPPAN', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-055', name: 'Mrs.T.KAVITHA', designation: 'Asst.Prof', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-056', name: 'MS.NIVEDHA', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-057', name: 'Mrs.D.K.Geriyaasakthi', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-058', name: 'MS.T.ANGELINE', designation: 'Faculty', department: 'AI & DS', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  // Real service-course faculty from other departments who teach AI&DS Year 2
  // Semester III sections (Mathematics, Constitution of India, Employability
  // Skills) per the department's own Semester III timetable -- not AI&DS
  // faculty themselves, so tagged with their real teaching department.
  { id: 'FAC-059', name: 'Dr.R.JEGAN', designation: 'Faculty', department: 'Mathematics', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-060', name: 'Dr.R.SUDHARANI', designation: 'Faculty', department: 'Mathematics', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-061', name: 'Dr.E.JANAKI', designation: 'Faculty', department: 'Mathematics', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-062', name: 'Dr.M.KAVITHA', designation: 'Faculty', department: 'Mathematics', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-063', name: 'Mrs.Valarmathi', designation: 'Faculty', department: 'Legal Studies / Mandatory Courses', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-064', name: 'Mrs.Sangeetha', designation: 'Faculty', department: 'Legal Studies / Mandatory Courses', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-065', name: 'Dr.Selvakumari', designation: 'Faculty', department: 'Legal Studies / Mandatory Courses', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-066', name: 'Mrs.Anitha Florence', designation: 'Faculty', department: 'Humanities & Sciences', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
  { id: 'FAC-067', name: 'Mrs.Debbi Sharon', designation: 'Faculty', department: 'Humanities & Sciences', role: 'FACULTY', maxDailyPeriods: 6, maxWeeklyPeriods: 24 },
]
