// Regulation 2024 B.Tech AI & DS Complete Curriculum Roster (Semesters I-VIII)
// Source of Truth: Department Syllabus (Regulation 2024)

export interface SyllabusSubject {
  id: string
  code: string
  name: string
  credits: number
  deliveryType: 'THEORY' | 'INTEGRATED' | 'LAB' | 'PROJECT'
  category: string
  year: string // 'Year 1' | 'Year 2' | 'Year 3' | 'Year 4'
  semester: string // 'I' | 'II' | 'III' | 'IV' | 'V' | 'VI' | 'VII' | 'VIII'
  theoryPeriods: number
  labPeriods: number
  vertical?: string | null
}

export const REGULATION_2024_CURRICULUM: SyllabusSubject[] = [
  {
    "id": "SUB-23MA1101",
    "code": "23MA1101",
    "name": "Matrices and Calculus",
    "credits": 4,
    "deliveryType": "THEORY",
    "category": "BASIC_SCIENCE",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23PH1103",
    "code": "23PH1103",
    "name": "Engineering Physics",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "BASIC_SCIENCE",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23ES1106",
    "code": "23ES1106",
    "name": "Programming in C",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "ENGINEERING_SCIENCE",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ES1102",
    "code": "23ES1102",
    "name": "Basic Electrical and Electronics Engineering",
    "credits": 4,
    "deliveryType": "INTEGRATED",
    "category": "ENGINEERING_SCIENCE",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23HS1103",
    "code": "23HS1103",
    "name": "Communicative English and Language Skills I",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "HUMANITIES",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23ES1113",
    "code": "23ES1113",
    "name": "Programming in C Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23ES1114",
    "code": "23ES1114",
    "name": "Innovative Thinking and Prototype Development",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23TA1101",
    "code": "23TA1101",
    "name": "Heritage of Tamils",
    "credits": 1,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1104",
    "code": "23HS1104",
    "name": "Interpersonal Communication Skills I",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1105",
    "code": "23HS1105",
    "name": "Quantitative Aptitude Practices I",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "I",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MA1203",
    "code": "23MA1203",
    "name": "Transforms and Vector Calculus",
    "credits": 4,
    "deliveryType": "THEORY",
    "category": "BASIC_SCIENCE",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1202",
    "code": "23AD1202",
    "name": "Data Structures and Analysis of Algorithms",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ES1206",
    "code": "23ES1206",
    "name": "Programming in Python",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "ENGINEERING_SCIENCE",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1203",
    "code": "23HS1203",
    "name": "Communicative English and Language Skills II",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "HUMANITIES",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1212",
    "code": "23AD1212",
    "name": "Data Structures and Analysis of Algorithms Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23ES1215",
    "code": "23ES1215",
    "name": "Programming in Python Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23TA1201",
    "code": "23TA1201",
    "name": "Tamils and Technology",
    "credits": 1,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ES1212",
    "code": "23ES1212",
    "name": "Technical Skill Practices I",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1204",
    "code": "23HS1204",
    "name": "Interpersonal Communication Skills II",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1205",
    "code": "23HS1205",
    "name": "Quantitative Aptitude Practices II",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 1",
    "semester": "II",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MA1304",
    "code": "23MA1304",
    "name": "Mathematical Foundations for Artificial Intelligence",
    "credits": 4,
    "deliveryType": "THEORY",
    "category": "BASIC_SCIENCE",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1301",
    "code": "23AD1301",
    "name": "Internals of Computer Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "ENGINEERING_SCIENCE",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1302",
    "code": "23AD1302",
    "name": "Artificial Intelligence and Expert Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1303",
    "code": "23AD1303",
    "name": "Object Oriented Programming Paradigm",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23CS1303",
    "code": "23CS1303",
    "name": "Database Management Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1311",
    "code": "23AD1311",
    "name": "Artificial Intelligence and Expert Systems Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23AD1312",
    "code": "23AD1312",
    "name": "Object Oriented Programming Paradigm Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23CS1312",
    "code": "23CS1312",
    "name": "Database Management Systems Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23ES1311",
    "code": "23ES1311",
    "name": "Technical Skill Practices II",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1301",
    "code": "23HS1301",
    "name": "Skills for Career Building and Development I",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1302",
    "code": "23HS1302",
    "name": "Quantitative Aptitude Practices III",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "III",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MA1405",
    "code": "23MA1405",
    "name": "Probability and Statistical Techniques for Data Science",
    "credits": 4,
    "deliveryType": "THEORY",
    "category": "BASIC_SCIENCE",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1401",
    "code": "23AD1401",
    "name": "Machine Learning",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1402",
    "code": "23AD1402",
    "name": "Basics of Data Science",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1403",
    "code": "23AD1403",
    "name": "Software Development and Practices",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1404",
    "code": "23AD1404",
    "name": "System Software and Operating Systems",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1411",
    "code": "23AD1411",
    "name": "Machine Learning Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23AD1412",
    "code": "23AD1412",
    "name": "Data Science Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23ES1411",
    "code": "23ES1411",
    "name": "Technical Skill Practices III",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1401",
    "code": "23HS1401",
    "name": "Skills for Career Building and Development II",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23HS1402",
    "code": "23HS1402",
    "name": "Quantitative Aptitude Practices IV",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 2",
    "semester": "IV",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1501",
    "code": "23AD1501",
    "name": "Formal Language and Automata Theory",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1502",
    "code": "23AD1502",
    "name": "Data Communication and Network Security",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1505",
    "code": "23AD1505",
    "name": "Data Exploration and Visualization",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1506",
    "code": "23AD1506",
    "name": "Data Analytics",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1507",
    "code": "23AD1507",
    "name": "Knowledge Engineering and Intelligent Systems",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1511",
    "code": "23AD1511",
    "name": "Data Analytics Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23AD1512",
    "code": "23AD1512",
    "name": "Knowledge Engineering and Intelligent Systems",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23AD1513",
    "code": "23AD1513",
    "name": "Technical Seminar and Research Writing",
    "credits": 1,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ES1511",
    "code": "23ES1511",
    "name": "Technical Skill Practices IV",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 3",
    "semester": "V",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1601",
    "code": "23AD1601",
    "name": "Deep Learning",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1603",
    "code": "23AD1603",
    "name": "Business Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1605",
    "code": "23AD1605",
    "name": "Computer Vision",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1606",
    "code": "23AD1606",
    "name": "AI in Robotics",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1611",
    "code": "23AD1611",
    "name": "Deep Learning Laboratory",
    "credits": 2,
    "deliveryType": "LAB",
    "category": "LABORATORY",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 0,
    "labPeriods": 3,
    "vertical": null
  },
  {
    "id": "SUB-23ES1611",
    "code": "23ES1611",
    "name": "Technical Skill Practices V",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "EMPLOYABILITY",
    "year": "Year 3",
    "semester": "VI",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ML1702",
    "code": "23ML1702",
    "name": "Natural Language Processing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1704",
    "code": "23AD1704",
    "name": "GenAI Tools and Techniques",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23AD1705",
    "code": "23AD1705",
    "name": "Augmented Reality and Virtual Reality with AI",
    "credits": 3,
    "deliveryType": "INTEGRATED",
    "category": "PROFESSIONAL_CORE",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 3,
    "labPeriods": 2,
    "vertical": null
  },
  {
    "id": "SUB-23HS1701",
    "code": "23HS1701",
    "name": "Climate Change and Sustainability",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "HUMANITIES",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1712",
    "code": "23AD1712",
    "name": "Mini Project",
    "credits": 2,
    "deliveryType": "PROJECT",
    "category": "PROJECT",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 0,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1703",
    "code": "23AD1703",
    "name": "Industrial Training / Internship",
    "credits": 1,
    "deliveryType": "THEORY",
    "category": "PROJECT",
    "year": "Year 4",
    "semester": "VII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1811",
    "code": "23AD1811",
    "name": "Project Work",
    "credits": 8,
    "deliveryType": "PROJECT",
    "category": "PROJECT",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 0,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23AD1901",
    "code": "23AD1901",
    "name": "Data Warehousing and Data Mining",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1902",
    "code": "23AD1902",
    "name": "Exploratory Data Analysis",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1903",
    "code": "23AD1903",
    "name": "Soft Computing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1904",
    "code": "23AD1904",
    "name": "Text Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1905",
    "code": "23AD1905",
    "name": "Recommender Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1906",
    "code": "23AD1906",
    "name": "Engineering Predictive Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1907",
    "code": "23AD1907",
    "name": "Ethics in AI",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23AD1908",
    "code": "23AD1908",
    "name": "Big Data Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL I \u2014 DATA SCIENCE & OPTIMIZATION"
  },
  {
    "id": "SUB-23IT1901",
    "code": "23IT1901",
    "name": "Next Gen Web Development",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1902",
    "code": "23IT1902",
    "name": "Open Source Technologies",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1903",
    "code": "23IT1903",
    "name": "App Development",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1904",
    "code": "23IT1904",
    "name": "UI and UX Design",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1905",
    "code": "23IT1905",
    "name": "DevOps",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1906",
    "code": "23IT1906",
    "name": "Software Testing and Automation",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1923",
    "code": "23IT1923",
    "name": ".NET Full Stack Web Application Development",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL II \u2014 FULL STACK DEVELOPMENT"
  },
  {
    "id": "SUB-23IT1908",
    "code": "23IT1908",
    "name": "Project Management and Agile Technologies",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "PROJECT",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23CS1901",
    "code": "23CS1901",
    "name": "Storage Technologies",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1902",
    "code": "23CS1902",
    "name": "Cloud Tools and Techniques",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1903",
    "code": "23CS1903",
    "name": "Virtualization",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1904",
    "code": "23CS1904",
    "name": "Cloud Services Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1905",
    "code": "23CS1905",
    "name": "Security and Privacy in Cloud",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1906",
    "code": "23CS1906",
    "name": "Stream Processing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1907",
    "code": "23CS1907",
    "name": "Site Reliability Engineering",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23CS1908",
    "code": "23CS1908",
    "name": "Quantum Computing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL III \u2014 CLOUD COMPUTING & DATA CENTER TECHNOLOGIES"
  },
  {
    "id": "SUB-23IT1909",
    "code": "23IT1909",
    "name": "Ethical Hacking",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1910",
    "code": "23IT1910",
    "name": "Modern Cryptography",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1911",
    "code": "23IT1911",
    "name": "Digital and Mobile Forensics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1912",
    "code": "23IT1912",
    "name": "Social Network Security",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1913",
    "code": "23IT1913",
    "name": "Cryptocurrency and Blockchain Technologies",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1914",
    "code": "23IT1914",
    "name": "Engineering Secure Software Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1915",
    "code": "23IT1915",
    "name": "Cyber Physical Systems Security",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23IT1916",
    "code": "23IT1916",
    "name": "Threat Detection and Incident Response",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL IV \u2014 CYBER SECURITY & DATA PRIVACY"
  },
  {
    "id": "SUB-23CS1909",
    "code": "23CS1909",
    "name": "Video Creation and Editing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1910",
    "code": "23CS1910",
    "name": "Digital Marketing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1911",
    "code": "23CS1911",
    "name": "Multimedia and Animation",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1912",
    "code": "23CS1912",
    "name": "Streaming Media Tools and Technologies",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1913",
    "code": "23CS1913",
    "name": "Visual Effects",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1914",
    "code": "23CS1914",
    "name": "3D Printing and Design",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1915",
    "code": "23CS1915",
    "name": "Game Development",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23AD1909",
    "code": "23AD1909",
    "name": "Data Visualization",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL V \u2014 CREATIVE MEDIA"
  },
  {
    "id": "SUB-23CS1917",
    "code": "23CS1917",
    "name": "Communication Theory",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23CS1918",
    "code": "23CS1918",
    "name": "Network Design and Programming",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23IT1917",
    "code": "23IT1917",
    "name": "Network Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23IT1918",
    "code": "23IT1918",
    "name": "Wireless Technologies",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23CS1919",
    "code": "23CS1919",
    "name": "Wireless Adhoc and Sensor Networks",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23IT1919",
    "code": "23IT1919",
    "name": "Protocols and Architectures for Wireless Sensor Networks",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23IT1920",
    "code": "23IT1920",
    "name": "Software Defined Networks",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23CS1920",
    "code": "23CS1920",
    "name": "Next Generation Networks",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VI \u2014 NETWORKING"
  },
  {
    "id": "SUB-23AD1910",
    "code": "23AD1910",
    "name": "Image and Video Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1911",
    "code": "23AD1911",
    "name": "Speech Processing and Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1912",
    "code": "23AD1912",
    "name": "Health Care Analytics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1913",
    "code": "23AD1913",
    "name": "Optimization Techniques",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1914",
    "code": "23AD1914",
    "name": "Bio Inspired Optimization Computing",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1915",
    "code": "23AD1915",
    "name": "Game Theory",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1916",
    "code": "23AD1916",
    "name": "Cognitive Science",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23AD1917",
    "code": "23AD1917",
    "name": "Robotic Process Automation and Development",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "PROFESSIONAL_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": "VERTICAL VII \u2014 INTELLIGENT ANALYTICS"
  },
  {
    "id": "SUB-23CE1010",
    "code": "23CE1010",
    "name": "Air Pollution and Control Engineering",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ME1008",
    "code": "23ME1008",
    "name": "Energy Conservation and Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23GE1004",
    "code": "23GE1004",
    "name": "Hospital Waste Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ME1009",
    "code": "23ME1009",
    "name": "Industrial Nanotechnology",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EE1003",
    "code": "23EE1003",
    "name": "Logic and Distributed Control Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EC1011",
    "code": "23EC1011",
    "name": "Telehealth Technology",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EE1001",
    "code": "23EE1001",
    "name": "Basic Circuit Theory",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ME1010",
    "code": "23ME1010",
    "name": "Energy Engineering",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EC1004",
    "code": "23EC1004",
    "name": "Electronic Devices",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23CE1009",
    "code": "23CE1009",
    "name": "Environmental and Social Impact Assessment",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23GE1003",
    "code": "23GE1003",
    "name": "Hospital Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EC1002",
    "code": "23EC1002",
    "name": "Medical Electronics",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23EC1009",
    "code": "23EC1009",
    "name": "Signals and Systems",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ME1006",
    "code": "23ME1006",
    "name": "Systems Engineering",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23ME1944",
    "code": "23ME1944",
    "name": "Supply Chain Management",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23CY1003",
    "code": "23CY1003",
    "name": "Waste Water Treatment",
    "credits": 3,
    "deliveryType": "THEORY",
    "category": "OPEN_ELECTIVE",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1001",
    "code": "23MC1001",
    "name": "Environmental Science",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1002",
    "code": "23MC1002",
    "name": "Constitution of India",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1003",
    "code": "23MC1003",
    "name": "Human Values",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1004",
    "code": "23MC1004",
    "name": "Energy Studies",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1005",
    "code": "23MC1005",
    "name": "Essence of Indian Traditional Knowledge",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1006",
    "code": "23MC1006",
    "name": "Soft Skills and Personality Development",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1007",
    "code": "23MC1007",
    "name": "Value Education, Human Rights and Legislature Procedure",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  },
  {
    "id": "SUB-23MC1008",
    "code": "23MC1008",
    "name": "Disaster Management",
    "credits": 0,
    "deliveryType": "THEORY",
    "category": "MANDATORY",
    "year": "Year 4",
    "semester": "VIII",
    "theoryPeriods": 3,
    "labPeriods": 0,
    "vertical": null
  }
];
