export type Page =
  | 'login'
  | 'dashboard'
  | 'faculty'
  | 'subjects'
  | 'data-hub'
  | 'upload-curriculum'
  | 'upload-workload'
  | 'constraints'
  | 'generate'
  | 'timetable-result'
  | 'view-timetable'
  | 'edit-timetable'
  | 'reports'
  | 'settings'
  | 'about'
